### ISSUE TITLE
[BUG] ENTIRE APP NOT WORKING ANYMORE

### ISSUE THREAD

**Issue by dfsssssssgg** [AssetKid/raider-release#107] opened 2022-04-04 00:22 UTC
Unable to download anything with raider since April's fool. sigh, are we all going to be forced back to 4k stogram? that program is shit man

**Comment by KaunWho** [comment] 2022-04-16 07:17
It's dead. Is there an alternate that you've found for it?

**Comment by dfsssssssgg** [comment] 2022-04-16 07:56
Back to 4k stogram... for now

**Comment by Kvasmuppet** [comment] 2022-04-24 10:40
Update your useragent in the app settings. Raider is working perfectly fine for me without any issue whatsoever, but you have to update the useragent settings every now and then.

**Comment by AssetKid** [comment] 2022-04-26 10:19
I am assuming this is related to your previous issue #106.

I have left a comment with some recommendations.

https://github.com/AssetKid/raider-release/issues/106#issuecomment-1109606596

If the issue is still happening, take a look at the log and let me know which error message you're getting.

![image](https://user-images.githubusercontent.com/40426812/165278498-29f1030a-4340-49c6-ab80-b338eb9ccb24.png)

Closing this for now.

**Closed by AssetKid** 2022-04-26 10:19 UTC
