### ISSUE TITLE
[BUG] Can't Open Raider after Update to 1.6.0

### ISSUE THREAD

**Issue by suxxxbang** [AssetKid/raider-release#69] opened 2020-11-24 04:26 UTC
Recently, the app ask me to update to the latest version and I did, but this happen when I tried to use the new update. Any solution? Thank you
![Screenshot_1](https://user-images.githubusercontent.com/68200969/100048651-ea191480-2e47-11eb-80df-faa080e055df.jpg)

**Comment by KaunWho** [comment] 2020-11-24 04:57
I just downloaded the new version as a complete package and installed it and it seems to be working just fine for me. System W10. Try downloading the complete installer or the portable version.

**Comment by AssetKid** [comment] 2020-11-25 19:23
I have not been able to reproduce this on my PC and several virtual machines.

Try closing all instance of Raider from the task manager then install the new version. Download a fresh copy of the installer just to be sure.

**Closed by AssetKid** 2020-11-25 19:23 UTC
Labels: status: can't reproduce, type: bug
